// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://wjlmmgpymfhdybrxncmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqbG1tZ3B5bWZoZHlicnhuY21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMzkyMzIsImV4cCI6MjA1NDgxNTIzMn0.f5ABg2KcbjlG7jiaGkNZetiB5jzDYIfJ2DR89y8_4hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);